booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('calendar', views.calendar, name='calendar'),
    path('', views.BookingListView.as_view(), name='list'),
    path('add', views.BookingCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', views.BookingsUpdate.as_view(), name='update'),

    path('<int:pk>/delete/', views.BookingDelete.as_view(), name='delete'),
    path('store/', views.store_booking, name="store"),
    path('update/<int:pk>/', views.update_booking, name="custom_update"),
    path('get_events_json/', views.booking_events_json, name="get_events_json"),
    path('get_booking_json/<int:pk>/', views.booking_json_modal, name="get_booking_json"),
    path('time_calendar/', views.timeCalendar, name="time_calendar"),
    path('get_slots_json/', views.timeCalendar_json, name="slots_json"),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', include('administrator.urls'), name="administrator"),
                  path('services/', include('services.urls'), name="services"),
                  path('booking/', include('booking.urls'), name="booking"),
                  path('projects/', include('projects.urls'), name="projects"),
                  path('customer/', include('customer.urls'), name="customer"),
                  path('staff/', include('staff.urls'), name="staff"),
                  path('user/', include('users.urls'), name="users"),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('allauth.urls'), name="accounts"),
                  path('i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projectsview, name='list'),
    path('<int:pk>/', views.BookingView.as_view(), name='view'),
    path('create_dir/', views.testingdir, name="create_dir"),
    path('delete_folder/', views.delete_folder, name="delete_folder"),
    path('rename_folder_file/', views.rename_folder_file, name='rename_folder_file'),

    # File Manager URls
    path('create_folder/', views.folder_create, name='folder_create'),
    path('get_filemanager_content/<int:pk>', views.filemanager_content, name="filemanager_content"),
    path('get_filemanager_content_public/<pk>', views.filemanager_content_public,
         name="filemanager_content_public"),

    # admin url
    path('get_filemanager_content_admin/', views.filemanager_content_admin, name="filemanager_content_admin"),

    path('upload_files_manager/', views.upload_files, name='upload_files_manager'),
    path('public_project_view/<int:pk>', views.public_project_view, name='public_project_view'),
    path('project/mosaic/<pk>', views.public_project_signed, name='public_project_signed'),
    path('download_zip_file/', views.download_zip, name='download_zip_file'),
    path('download_file/', views.download_zip_file, name='download_file'),
]

services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path('', views.ServicesListView.as_view(), name='list'),
    path('add', views.ServicesCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', views.ServicesUpdate.as_view(), name='update'),
    path('<int:pk>/', views.ServiceView.as_view(), name='view'),
    path('<int:pk>/delete/', views.ServiceDelete.as_view(), name='delete'),

    # ajax requests
    path('<int:type>/ajax/getServices', views.get_service, name='services_list_from_type'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('profile', views.ProfileView.as_view(), name='profile'),

]

templates/components/footer.html
<div class="footer-wrapper">
    <div class="footer-section f-section-1">
        <p class="">Copyright © 2020 <a target="_blank" href="#">Mosaic Media</a>, All
            rights reserved.</p>
    </div>
    <div class="footer-section f-section-2">
        <p class="">Coded with
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-heart">
                <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
            </svg>
        </p>
    </div>
</div>

templates/components/navbar.html
{% load i18n %}
{% load static %}
<!--  BEGIN NAVBAR  -->
<div class="header-container fixed-top">
    <header class="header navbar navbar-expand-sm">
        <ul class="navbar-item flex-row">
            <li class="nav-item theme-logo">
                <a href="/">
                    MOSAIC MEDIA
                </a>
            </li>
        </ul>

        <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-list">
                <line x1="8" y1="6" x2="21" y2="6"></line>
                <line x1="8" y1="12" x2="21" y2="12"></line>
                <line x1="8" y1="18" x2="21" y2="18"></line>
                <line x1="3" y1="6" x2="3" y2="6"></line>
                <line x1="3" y1="12" x2="3" y2="12"></line>
                <line x1="3" y1="18" x2="3" y2="18"></line>
            </svg>
        </a>

        <ul class="navbar-item flex-row search-ul">
            <li class="nav-item align-self-center search-animated">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="feather feather-search toggle-search">
                    <circle cx="11" cy="11" r="8"></circle>
                    <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                </svg>
                <form class="form-inline search-full form-inline search" role="search">
                    <div class="search-bar">
                        <input type="text" class="form-control search-form-control  ml-lg-auto" placeholder="Search...">
                    </div>
                </form>
            </li>
        </ul>
        <ul class="navbar-item flex-row navbar-dropdown">


            <li class="nav-item dropdown user-profile-dropdown  order-lg-0 order-1">
                <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="
                            {% if user.lenderprofile.first.picture %}{{ user.lenderprofile.first.picture.url }}{% else %}{% static 'assets/img/profile-7.jpg' %}{% endif %}"
                         alt="admin-profile" class="img-fluid">
                </a>
                <div class="dropdown-menu position-absolute animated fadeInUp" aria-labelledby="userProfileDropdown">
                    <div class="user-profile-section">
                        <div class="media mx-auto">
                            <img src="
                                    {% if user.lenderprofile.first.picture %}{{ user.lenderprofile.first.picture.url }}{% else %}{% static 'assets/img/profile-7.jpg' %}{% endif %}"
                                 class="img-fluid mr-2"
                                 alt="avatar">
                            <div class="media-body">
                                {% if request.user.is_authenticated %}
                                    <h5>
                                        {% if user.lenderprofile.first.firstName %}
                                            {{ user.lenderprofile.first.firstName }}
                                            {{ " " }}{{ user.lenderprofile.first.lastName }}
                                        {% else %}
                                            {{ user.username|title }}
                                        {% endif %}
                                    </h5>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="dropdown-item">
                            <a href="{% url 'users:profile' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                     fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round" class="feather feather-user">
                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                    <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                                <span>{% trans 'My Profile' %}</span>
                            </a>
                        </div>
                        <div class="dropdown-item">
                            <a href="{% url 'account_logout' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                     fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round" class="feather feather-log-out">
                                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                    <polyline points="16 17 21 12 16 7"></polyline>
                                    <line x1="21" y1="12" x2="9" y2="12"></line>
                                </svg>
                                <span>Log Out</span>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </li>
        </ul>
    </header>
</div>
<!--  END NAVBAR  -->

templates/components/preloader.html
<!-- BEGIN LOADER -->
<div id="load_screen">
    <div class="loader">
        <div class="loader-content">
            <div class="spinner-grow align-self-center"></div>
        </div>
    </div>
</div>
<!--  END LOADER -->

templates/components/sidebar.html
{% load i18n %}
{% load static %}
{% url 'administrator:index' as home_url %}
{% url 'services:list' as services_list %}
{% url 'booking:list' as booking_list %}
{% url 'booking:calendar' as calendar %}
{% url 'administrator:customers' as customers %}
{% url 'projects:list' as projects_view %}

<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">

    <nav id="compactSidebar">
        <ul class="menu-categories">

            <li class="menu {% if request.get_full_path == home_url %}active{% endif %}">
                <a href="/" data-active="true" class="menu-toggle">
                    <div class="base-menu">
                        <div class="base-icons">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round" class="feather feather-home">
                                <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                                <polyline points="9 22 9 12 15 12 15 22"></polyline>
                            </svg>
                        </div>
                        <span>{% trans 'Dashboard' %}</span>
                    </div>
                </a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="feather feather-chevron-left">
                    <polyline points="15 18 9 12 15 6"></polyline>
                </svg>
            </li>
            {% if request.user.is_superuser %}
                <li class="menu {% if request.get_full_path == calendar %}active{% endif %}">
                    <a href="{% url 'booking:calendar' %}" data-active="false" class="menu-toggle">
                        <div class="base-menu">
                            <div class="base-icons">
                                <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2"
                                     fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                                    <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                    <line x1="16" y1="2" x2="16" y2="6"></line>
                                    <line x1="8" y1="2" x2="8" y2="6"></line>
                                    <line x1="3" y1="10" x2="21" y2="10"></line>
                                </svg>
                            </div>
                            <span>{% trans 'Calendar' %}</span>
                        </div>
                    </a>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-chevron-left">
                        <polyline points="15 18 9 12 15 6"></polyline>
                    </svg>
                </li>
            {% endif %}
            <li class="menu {% if request.get_full_path == booking_list %}active{% endif %}">
                <a href="{% url 'booking:list' %}" data-active="false" class="menu-toggle">
                    <div class="base-menu">
                        <div class="base-icons">
                            <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2"
                                 fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                                <circle cx="12" cy="12" r="10"></circle>
                                <line x1="2" y1="12" x2="22" y2="12"></line>
                                <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
                            </svg>
                        </div>
                        <span>{% trans 'Bookings' %}</span>
                    </div>
                </a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="feather feather-chevron-left">
                    <polyline points="15 18 9 12 15 6"></polyline>
                </svg>
            </li>
            {% if request.user.is_superuser %}
                <li class="menu {% if request.get_full_path == projects_view %}active{% endif %}">
                    <a href="{% url 'projects:list' %}" data-active="false" class="menu-toggle">
                        <div class="base-menu">
                            <div class="base-icons">
                                <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2"
                                     fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                                    <polyline points="21 8 21 21 3 21 3 8"></polyline>
                                    <rect x="1" y="3" width="22" height="5"></rect>
                                    <line x1="10" y1="12" x2="14" y2="12"></line>
                                </svg>
                            </div>
                            <span>{% trans 'Projects' %}</span>
                        </div>
                    </a>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-chevron-left">
                        <polyline points="15 18 9 12 15 6"></polyline>
                    </svg>
                </li>
                <li class="menu {% if request.get_full_path == services_list %}active{% endif %}">
                    <a href="{% url 'services:list' %}" data-active="false" class="menu-toggle">
                        <div class="base-menu">
                            <div class="base-icons">
                                <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2"
                                     fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                                    <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path>
                                </svg>
                            </div>
                            <span>{% trans 'Services' %}</span>
                        </div>
                    </a>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-chevron-left">
                        <polyline points="15 18 9 12 15 6"></polyline>
                    </svg>
                </li>
                <li class="menu {% if request.get_full_path == customers %}active{% endif %}">
                    <a href="{% url 'administrator:customers' %}" data-active="false" class="menu-toggle">
                        <div class="base-menu">
                            <div class="base-icons">
                                <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2"
                                     fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                    <circle cx="9" cy="7" r="4"></circle>
                                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                    <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                                </svg>
                            </div>
                            <span class="">{% trans 'Customers' %}</span>
                        </div>
                    </a>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-chevron-left">
                        <polyline points="15 18 9 12 15 6"></polyline>
                    </svg>
                </li>
            {% endif %}

        </ul>
    </nav>
    <div id="compact_submenuSidebar" class="submenu-sidebar">
    </div>

</div>
<!--  END SIDEBAR  -->

templates/components/sorted_table.html
{% load i18n %}
{% load static %}
<div class="layout-px-spacing col-12">

    <div class="row layout-top-spacing" id="cancel-row">
        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <div class="widget-content widget-content-area br-6">
                <div class="table-responsive mb-4 mt-4">
                    <table id="default-ordering" class="table table-hover" style="width:100%">
                        <thead>
                        <tr>
                            <th>{% trans 'Date' %}</th>
                            <th>{% trans 'Picture' %}</th>
                            <th>{% trans 'First Name' %}</th>
                            <th>{% trans 'Last Name' %}</th>
                            <th>{% trans 'Amount' %}</th>
                            <th>{% trans 'Loan Type' %}</th>
                            <th>{% trans 'City' %}</th>
                            <th>{% trans 'Postal Code' %}</th>
                            <th>{% trans 'Action' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for loan in loans %}
                            <tr>
                                <td>{{ loan.created_at }}</td>
                                <td>
                                    {% if loan.owner.socialaccount_set.all.0.get_avatar_url %}
                                        <img class="img-fluid rounded-circle" style="height: 40px;"
                                             src="{{ loan.owner.socialaccount_set.all.0.get_avatar_url }}"
                                             alt="{{ loan.owner.username }}"/>
                                    {% else %}
                                        <img alt="avatar" class="img-fluid rounded-circle" style="height: 40px;"
                                             src="{% static 'lenderer/assets/img/boy.png' %}">
                                    {% endif %}
                                </td>
                                <td>{{ loan.profile.firstName }}</td>
                                <td>{{ loan.profile.lastName }}</td>
                                <td>{{ loan.amount }}</td>
                                <td>{{ loan.get_loanType_display }}</td>
                                <td>{{ loan.profile.city }}</td>
                                <td>{{ loan.profile.postcode }}</td>
                                <td class="text-center">
                                    <a href="{% url 'loan:request' loan.id %}"
                                       class="btn btn-primary">{% trans 'View' %}</a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>{% trans 'Date' %}</th>
                            <th>{% trans 'Picture' %}</th>
                            <th>{% trans 'First Name' %}</th>
                            <th>{% trans 'Last Name' %}</th>
                            <th>{% trans 'Amount' %}</th>
                            <th>{% trans 'Loan Type' %}</th>
                            <th>{% trans 'City' %}</th>
                            <th>{% trans 'Postal Code' %}</th>
                            <th class="invisible"></th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>